// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/recipes": {
    params: {};
  };
  "/ingredients": {
    params: {};
  };
  "/consumption": {
    params: {};
  };
  "/waste": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/recipes" | "/ingredients" | "/consumption" | "/waste" | "/notifications" | "/login" | "/signup";
  };
  "components/dashboard/AdminLayout.jsx": {
    id: "components/dashboard/AdminLayout";
    page: "/" | "/recipes" | "/ingredients" | "/consumption" | "/waste" | "/notifications";
  };
  "components/dashboard/DashboardPage.jsx": {
    id: "components/dashboard/DashboardPage";
    page: "/";
  };
  "components/dashboard/RecipePage.jsx": {
    id: "components/dashboard/RecipePage";
    page: "/recipes";
  };
  "components/dashboard/IngredientPage.jsx": {
    id: "components/dashboard/IngredientPage";
    page: "/ingredients";
  };
  "components/dashboard/ConsumptionPage.jsx": {
    id: "components/dashboard/ConsumptionPage";
    page: "/consumption";
  };
  "components/dashboard/WasteManagementPage.jsx": {
    id: "components/dashboard/WasteManagementPage";
    page: "/waste";
  };
  "components/notifications/NotificationsPage.jsx": {
    id: "components/notifications/NotificationsPage";
    page: "/notifications";
  };
  "components/auth/Login.jsx": {
    id: "components/auth/Login";
    page: "/login";
  };
  "components/auth/Signup.jsx": {
    id: "components/auth/Signup";
    page: "/signup";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/dashboard/AdminLayout": typeof import("./app/components/dashboard/AdminLayout.jsx");
  "components/dashboard/DashboardPage": typeof import("./app/components/dashboard/DashboardPage.jsx");
  "components/dashboard/RecipePage": typeof import("./app/components/dashboard/RecipePage.jsx");
  "components/dashboard/IngredientPage": typeof import("./app/components/dashboard/IngredientPage.jsx");
  "components/dashboard/ConsumptionPage": typeof import("./app/components/dashboard/ConsumptionPage.jsx");
  "components/dashboard/WasteManagementPage": typeof import("./app/components/dashboard/WasteManagementPage.jsx");
  "components/notifications/NotificationsPage": typeof import("./app/components/notifications/NotificationsPage.jsx");
  "components/auth/Login": typeof import("./app/components/auth/Login.jsx");
  "components/auth/Signup": typeof import("./app/components/auth/Signup.jsx");
};